"""PLAN-153 Wave B item 5 — release-workflow VERSION-consistency + idempotency asserts.

Extends the existing VERSION-consistency test family
(test_npm_rebuild.py::NpmRebuildTest.test_version_files_in_sync —
VERSION == npm/VERSION == npm/package.json.version) and the grey-box
workflow-invariant convention (test_workflow_devops_p2.py) with:

- version↔plugin-manifest sync: VERSION == .claude-plugin/plugin.json
  version == every `version` field in .claude-plugin/marketplace.json
  (skip-if-absent until PLAN-153 Wave B item 6 generates the manifests
  via build-plugin.py — same skipTest pattern test_npm_rebuild.py uses
  for the release-only npm bundle);
- RC posture pins on npm-publish.yml: RC tags stay hard-excluded from
  npm publishing (PLAN-013 anti-goals #3/#16, re-ratified by the
  PLAN-153 debate: the `next` dist-tag idea was DROPPED);
- release-notes template invariants (.github/release-notes-template.md,
  closes PLAN-152 §Deferred release-notes-hardcoded-first-release);
- dual-context asserts on the Wave B workflow edits themselves
  (npm-publish.yml `already_published` guard; release.yml
  `gh release view || gh release create` idempotency; `-rc.N` strip in
  the VERSION + CHANGELOG gates, closing PLAN-152 §Deferred
  release-gate-rc-version-mismatch / red run 28663453202): enforced
  against the STAGED copy while it exists on disk
  (.claude/plans/PLAN-153/staged/wave-B/ is gitignored → absent in CI)
  and against the LIVE workflow once Wave B lands (detected via the
  "PLAN-153 Wave B item 5" marker). They skip only in the pre-landing
  CI window where neither context is available.
"""
from __future__ import annotations

import json
import re
import sys
import unittest
from pathlib import Path
from typing import Iterator, Optional, Tuple

_REPO = Path(__file__).resolve().parent.parent.parent.parent
_WF = _REPO / ".github" / "workflows"
_STAGED_WF = (
    _REPO / ".claude" / "plans" / "PLAN-153" / "staged" / "wave-B"
    / ".github" / "workflows"
)
_TEMPLATE = _REPO / ".github" / "release-notes-template.md"
_PLUGIN_DIR = _REPO / ".claude-plugin"

# Bootstrap TestEnvContext so env isolation holds (env-hygiene gate).
_HOOKS_DIR = _REPO / ".claude" / "hooks"
if str(_HOOKS_DIR) not in sys.path:
    sys.path.insert(0, str(_HOOKS_DIR))
from _lib.testing import TestEnvContext  # noqa: E402

# Marker written into both Wave B workflow edits; its presence in the
# LIVE file means Wave B has landed and the live copy is authoritative.
_MARKER = "PLAN-153 Wave B item 5"

# The load-bearing RC exclusion (PLAN-013 anti-goals #3/#16).
_RC_EXCLUSION = "!contains(github.ref, '-rc.')"


def _wave_b_text(name: str) -> Optional[Tuple[str, str]]:
    """Return (text, context) for a Wave B workflow, or None pre-landing.

    Priority: live copy carrying the Wave B marker (post-landing,
    authoritative) → staged copy (pre-landing, local ceremony mirror;
    gitignored so absent in CI) → None (pre-landing CI: skip).
    """
    live = (_WF / name).read_text(encoding="utf-8")
    if _MARKER in live:
        return live, "live"
    staged = _STAGED_WF / name
    if staged.is_file():
        return staged.read_text(encoding="utf-8"), "staged"
    return None


def _iter_version_fields(obj: object) -> Iterator[str]:
    """Yield every string-valued `version` field nested anywhere in obj."""
    if isinstance(obj, dict):
        for key, value in obj.items():
            if key == "version" and isinstance(value, str):
                yield value
            else:
                yield from _iter_version_fields(value)
    elif isinstance(obj, list):
        for item in obj:
            yield from _iter_version_fields(item)


class PluginManifestVersionSyncTest(TestEnvContext):
    """VERSION ↔ .claude-plugin manifest sync (Wave B item 5 (e)).

    Sits NEXT TO the existing family member
    test_npm_rebuild.py::test_version_files_in_sync, extending the
    equality chain to the plugin manifests generated by build-plugin.py
    (Wave B item 6). Skips while the manifests do not exist yet; becomes
    enforcing the moment item 6 lands — no test edit needed.
    """

    def setUp(self):
        super().setUp()
        self.version = (_REPO / "VERSION").read_text(encoding="utf-8").strip()

    def test_plugin_json_version_matches_version_file(self):
        plugin_json = _PLUGIN_DIR / "plugin.json"
        if not plugin_json.is_file():
            self.skipTest(
                ".claude-plugin/plugin.json not present yet "
                "(generated by PLAN-153 Wave B item 6 build-plugin.py)"
            )
        data = json.loads(plugin_json.read_text(encoding="utf-8"))
        self.assertIn(
            "version", data,
            ".claude-plugin/plugin.json must carry a version field",
        )
        self.assertEqual(
            data["version"], self.version,
            f"plugin.json version ({data['version']}) != VERSION "
            f"({self.version}) — regenerate via build-plugin.py",
        )

    def test_marketplace_json_versions_match_version_file(self):
        marketplace_json = _PLUGIN_DIR / "marketplace.json"
        if not marketplace_json.is_file():
            self.skipTest(
                ".claude-plugin/marketplace.json not present yet "
                "(generated by PLAN-153 Wave B item 6 build-plugin.py)"
            )
        data = json.loads(marketplace_json.read_text(encoding="utf-8"))
        # Schema is owned by build-plugin.py, so assert on EVERY nested
        # `version` field rather than hardcoding one JSON path.
        mismatched = [
            v for v in _iter_version_fields(data) if v != self.version
        ]
        self.assertEqual(
            mismatched, [],
            f"marketplace.json carries version field(s) {mismatched} != "
            f"VERSION ({self.version}) — regenerate via build-plugin.py",
        )


class NpmPublishRcPostureTest(TestEnvContext):
    """RC tags stay hard-excluded from npm publishing — LIVE workflow.

    PLAN-013 anti-goals #3/#16; PLAN-153 Wave B item 5 (f) explicitly
    keeps this posture UNCHANGED. These asserts run against the live
    workflow in every context (pre- and post-landing).
    """

    def setUp(self):
        super().setUp()
        self.source = (_WF / "npm-publish.yml").read_text(encoding="utf-8")

    def test_rc_exclusion_present(self):
        self.assertIn(
            _RC_EXCLUSION, self.source,
            "npm-publish.yml lost the RC tag exclusion — RC tags must "
            "NEVER trigger an npm publish (PLAN-013 anti-goals #3/#16)",
        )

    def test_rc_exclusion_precedes_publish_command(self):
        # Ordering sanity: the job-level guard must appear before any
        # `npm publish` invocation in the file.
        self.assertLess(
            self.source.index(_RC_EXCLUSION),
            self.source.index("npm publish --provenance"),
            "RC exclusion must guard the job containing the publish step",
        )

    def test_manual_approval_environment_gate_present(self):
        self.assertIn(
            "environment: production-npm", self.source,
            "the Owner-in-the-loop manual approval environment gate "
            "(PLAN-013 anti-goal #16) must stay on the publish job",
        )


class ReleaseNotesTemplateTest(TestEnvContext):
    """Template invariants for the templatized release notes (item 5 (d))."""

    def setUp(self):
        super().setUp()
        self.assertTrue(
            _TEMPLATE.is_file(),
            ".github/release-notes-template.md missing — the Wave B "
            "release.yml renders notes from it (fail-closed)",
        )
        self.source = _TEMPLATE.read_text(encoding="utf-8")

    def test_has_tag_placeholder(self):
        self.assertIn("{{TAG}}", self.source)

    def test_has_base_version_placeholder(self):
        # BASE_VERSION (= VERSION minus -rc.N) points RC notes at the
        # GA CHANGELOG section.
        self.assertIn("{{BASE_VERSION}}", self.source)

    def test_no_stale_release_specific_hardcode(self):
        # The exact stale string this template replaces (PLAN-152
        # §Deferred release-notes-hardcoded-first-release).
        self.assertNotIn("first public release", self.source)

    def test_only_known_placeholders_used(self):
        # The workflow substitutes exactly TAG/VERSION/BASE_VERSION and
        # fails closed on any '{{' left after rendering; an unknown
        # token here would brick every release.
        unknown = set(re.findall(r"\{\{([^}]*)\}\}", self.source)) - {
            "TAG", "VERSION", "BASE_VERSION",
        }
        self.assertEqual(unknown, set(), f"unknown placeholders: {unknown}")


class WorkflowHygieneTest(TestEnvContext):
    """Parse + SHA-pin discipline for both tag-triggered workflows."""

    def test_workflows_parse_as_yaml(self):
        try:
            import yaml  # type: ignore
        except ImportError:  # pragma: no cover - CI installs pyyaml
            self.skipTest("pyyaml not installed")
        for name in ("release.yml", "npm-publish.yml"):
            for path in ((_WF / name), (_STAGED_WF / name)):
                if not path.is_file():
                    continue
                with self.subTest(path=str(path)):
                    data = yaml.safe_load(path.read_text(encoding="utf-8"))
                    self.assertIsInstance(data, dict)
                    self.assertIn("jobs", data)

    def test_all_action_uses_are_sha_pinned(self):
        # Every `uses:` in both workflows (live + staged copies) must
        # pin to a 40-hex commit SHA — no floating tags.
        pattern = re.compile(r"^\s*(?:-\s+)?uses:\s*(\S+)", re.MULTILINE)
        pinned = re.compile(r".+@[0-9a-f]{40}$")
        for name in ("release.yml", "npm-publish.yml"):
            for path in ((_WF / name), (_STAGED_WF / name)):
                if not path.is_file():
                    continue
                text = path.read_text(encoding="utf-8")
                for used in pattern.findall(text):
                    with self.subTest(path=str(path), uses=used):
                        self.assertRegex(
                            used, pinned,
                            f"{path.name}: `uses: {used}` is not "
                            "SHA-pinned to a 40-hex commit",
                        )


class WaveB5ReleaseYmlTest(TestEnvContext):
    """Wave B item 5 edits to release.yml (dual-context: staged/live)."""

    def setUp(self):
        super().setUp()
        resolved = _wave_b_text("release.yml")
        if resolved is None:
            self.skipTest(
                "Wave B release.yml not landed and staged mirror absent "
                "(pre-landing CI window)"
            )
        self.source, self.context = resolved

    def test_version_gate_strips_rc_suffix(self):
        # PLAN-152 §Deferred release-gate-rc-version-mismatch fix:
        # the tag is normalized before comparing against VERSION.
        self.assertIn('BASE="${EXPECTED%-rc.[0-9]*}"', self.source)
        self.assertIn('if [[ "$FILE" != "$BASE" ]]', self.source)

    def test_changelog_gate_strips_rc_suffix(self):
        # Without this the fixed VERSION gate would just move the RC
        # red run one step later (RC tags have no own CHANGELOG section).
        self.assertIn('VERSION="${VERSION%-rc.[0-9]*}"', self.source)

    def test_plugin_manifest_sync_step_present(self):
        self.assertIn(
            "Assert plugin manifest versions match VERSION", self.source
        )
        self.assertIn(".claude-plugin/plugin.json", self.source)
        self.assertIn(".claude-plugin/marketplace.json", self.source)

    def test_release_create_is_idempotent(self):
        # `gh release view || gh release create` shape: re-runs re-sync
        # assets instead of failing on the existing release.
        self.assertIn('if gh release view "$TAG"', self.source)
        self.assertIn("--clobber install.sh.sha256 sbom.cyclonedx.json",
                      self.source)
        self.assertIn('gh release create "$TAG"', self.source)

    def test_rc_tags_marked_prerelease(self):
        self.assertIn("--prerelease", self.source)

    def test_notes_are_templatized_not_hardcoded(self):
        self.assertIn("release-notes-template.md", self.source)
        self.assertIn("--notes-file release-notes.md", self.source)
        self.assertNotIn(
            "first public release", self.source,
            "stale per-release hardcode back in release.yml "
            "(PLAN-152 §Deferred release-notes-hardcoded-first-release)",
        )


class WaveB5NpmPublishYmlTest(TestEnvContext):
    """Wave B item 5 edits to npm-publish.yml (dual-context: staged/live)."""

    def setUp(self):
        super().setUp()
        resolved = _wave_b_text("npm-publish.yml")
        if resolved is None:
            self.skipTest(
                "Wave B npm-publish.yml not landed and staged mirror "
                "absent (pre-landing CI window)"
            )
        self.source, self.context = resolved

    def test_already_published_guard_present(self):
        self.assertIn("id: already_published", self.source)
        self.assertIn(
            'npm view "${PKG_NAME}@${PKG_VERSION}" version', self.source
        )

    def test_publish_step_gated_on_guard(self):
        self.assertIn(
            "if: steps.already_published.outputs.published != 'true'",
            self.source,
        )

    def test_noop_success_path_is_explicit(self):
        self.assertIn(
            "if: steps.already_published.outputs.published == 'true'",
            self.source,
        )

    def test_rc_exclusion_survives_wave_b(self):
        # Item 5 (f): the Wave B edit must NOT weaken the RC posture.
        self.assertIn(_RC_EXCLUSION, self.source)
        self.assertIn("environment: production-npm", self.source)


if __name__ == "__main__":
    unittest.main()
