#!/usr/bin/env python3
"""Classifier for the install/upgrade parity e2e (PLAN-166 W0 / F4, OQ-4).

Driver: scripts/tests/test-install-upgrade-parity-e2e.sh (read its header for
the why). This module owns the MEASUREMENT and the DECLARATIONS.

The instrument
--------------
Two adopter trees are handed in:

    A = install.sh (working tree)
    B = install.sh @ <pin>  ->  upgrade.sh (working tree)

For every path A delivered, B's bytes are classified against BOTH source
generations, so the verdict is about the *generation of framework content the
adopter ends up running*, not about byte-equality of two installs:

    IDENTICAL     A(p) == B(p)
    PERSONALIZED  B(p) == head_src(p)  -- upgrade shipped CURRENT framework
                  bytes; install.sh additionally substitutes {{PROJECT_NAME}}
                  and friends.  Advisory: content generation is correct.
    STALE         B(p) == pin_src(p) != head_src(p)  -- the upgrade left the
                  OLD generation in place.  This is F3's exact signature and
                  it is FATAL.
    MISSING_IN_B  install delivered p, upgrade never did.  FATAL.
    UNCLASSIFIED  diverges and matches neither generation.  FATAL unless the
                  path is DECLARED below (generated / adopter-owned).

Plus, from the other direction, ONLY_IN_B: content upgrade.sh's `cp -R` drags
in that install.sh's selective walk never ships. Advisory in general (ADR-155
documents this as pre-existing install/upgrade drift, and making it fatal today
would only get it neutered by an allowlist), FATAL when it lands outside
`.claude/` in `--ceremony user` mode, because that is the WS4 invariant
smoke-install.yml already asserts for install and nobody asserts for upgrade.

And MODE_DIFF: same bytes, different executable bit. Bytes-only comparison is
blind to it, and "cp lost the exec bit" is a verified failure mode of this repo
(S286). A hook or script that arrives non-executable through one route and
executable through the other is a real delivery divergence, so it is FATAL.

W1 CHECKLIST (do not skip)
--------------------------
Every KNOWN_OPEN entry below is MANDATORY-FIRE. When PLAN-166 W1 lands the F3
fix, those entries stop matching and this classifier goes FATAL on ledger-rot
BY DESIGN. Deleting them is part of the W1 commit, in the same commit as the
upgrade.sh/_framework_manifest_set.sh change — that is the mechanism that keeps
a ledger from outliving its bug, not an accident. EXPECT_PATHS is the opposite
shape on purpose: its entries are NOT deleted at W1 — they go quiet when
satisfied and stay behind as permanent existence asserts (see that list's own
comment).

Anti-rot
--------
Declarations decay, so both directions are checked:

  * KNOWN_OPEN entries are MANDATORY-FIRE. An entry that matches nothing is
    FATAL: the bug it names is closed, so the entry must be deleted. A ledger
    can never outlive its bug.
  * ACCEPTED entries that turn out IDENTICAL emit a WARNING (stale declaration,
    harmless).
  * Any divergence matching no declaration at all is FATAL. That is the live
    gate; the driver's --positive-control trips exactly there.

Exit: 0 parity | 1 fatal | 2 only KNOWN_OPEN outstanding.
Python >= 3.9, stdlib only.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from typing import Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Structural skips: never framework content, never comparable.
# ---------------------------------------------------------------------------
SKIP_DIRS = (".git", ".claude.bak", "__pycache__")
SKIP_SUFFIX = (".pyc",)

# ---------------------------------------------------------------------------
# ACCEPTED divergence — generated per-install or adopter-owned by contract.
# Every entry carries the AUTHORITY for the claim, not a shrug. These are
# printed as their own census block on every run so the list cannot grow
# quietly.
#   (regex, applies-to-modes or None for all, reason)
# ---------------------------------------------------------------------------
ACCEPTED: List[Tuple[str, Optional[str], str]] = [
    (
        r"^\.claude/\.install-manifest\.sha256$",
        None,
        "derived baseline manifest — regenerated by BOTH routes "
        "(_write_baseline_manifest); it is a hash OF the set under comparison, "
        "so comparing it would be circular",
    ),
    (
        r"^\.claude/\.install-state\.json$",
        None,
        "records the invocation itself (argv, timestamps, source sha, upgrade "
        "ops) — differs by construction between a fresh install and an "
        "install+upgrade; the `ceremony` field is asserted separately below",
    ),
    (
        r"^\.claude/settings\.json$",
        None,
        "install seeds it; upgrade does an ADDITIVE hook merge (PLAN-135 W2 H8) "
        "plus the 3-state baseline migration (PLAN-163 T5.4) and never "
        "clobbers — the two routes converge on keys, not on bytes",
    ),
    (
        r"^\.claude/agent-metrics\.md$",
        None,
        "adopter data — upgrade.sh header: 'Leaves CLAUDE.md, MEMORY.md, "
        ".claude/agent-metrics.md untouched'",
    ),
    (
        r"^(CLAUDE|MEMORY)\.md$",
        None,
        "seed-once adopter doc — same upgrade.sh preserve contract",
    ),
    (
        r"^PROTOCOL\.md$",
        "maintainer",
        "generated pointer. install.sh substitutes the resolved SOURCE_DIR; "
        "upgrade.sh's _refresh_protocol_pointer emits the literal "
        "{{PROTOCOL_SOURCE}} placeholder. Body-only divergence, pre-existing "
        "asymmetry of the same pointer file",
    ),
    (
        r"^VERSION$",
        "maintainer",
        "BY DESIGN (PLAN-166 OQ-3 / ADR-155-AMEND-1): the upgrade must NOT "
        "touch the adopter's root VERSION — install_one is skip-if-exists, so "
        "in an adopter that owns a VERSION the framework never wrote there and "
        "backup_and_replace would TAKE the file (the verified S238 worst "
        "case). The framework's own version marker moves to "
        ".claude/.framework-version. Asserted positively below: B/VERSION must "
        "be byte-identical to the pinned source's VERSION (untouched), not "
        "merely different",
    ),
]

# ---------------------------------------------------------------------------
# KNOWN_OPEN — PLAN-166 W1 prerequisites. MANDATORY-FIRE (see module docstring).
#   id, modes (None = all), class, regex, reason, unblocked_by
# ---------------------------------------------------------------------------
KNOWN_OPEN: List[Dict[str, Optional[str]]] = [
    # (empty — PLAN-166 W1 landed. F3-spec-stale and F3-protocol-user-mode
    # were deleted IN the W1 ceremony commit, per the mandatory-fire
    # contract above: a ledger can never outlive its bug. Add new entries
    # here ONLY with a mandatory-fire reason + unblocked_by.)
]


# Paths that must EXIST in both routes once W1 lands. Absent today, so each
# reports as KNOWN-OPEN (class=expect-path) and holds the run at exit 2.
# DELIBERATELY NOT mandatory-fire, unlike KNOWN_OPEN above: once the path
# exists in both trees the entry goes quiet and remains as a PERMANENT
# existence assert — it re-fires if either route ever stops delivering the
# marker. No W1 deletion is required for these. Content freshness of a path
# that IS present is not this list's job either: a present-but-stale marker
# is caught by the main classification loop (STALE there is FATAL).
EXPECT_PATHS: List[Dict[str, Optional[str]]] = [
    {
        "id": "F3-framework-version-marker",
        "modes": None,
        "path": ".claude/.framework-version",
        "reason": (
            "OQ-3 moves the framework's own version marker off the adopter's "
            "root VERSION and into .claude/.framework-version, as a TRACKED "
            "file of the framework repo written explicitly by BOTH install "
            "(install_one) and upgrade. Until it exists there is no surface on "
            "which install and upgrade can agree about which framework "
            "generation the adopter is running, and "
            "check-framework-updates.sh keeps resolving the stale root VERSION"
        ),
        "unblocked_by": "PLAN-166 W1 item 2 / OQ-3 (marker) + AC-3",
    },
]


def _norm_bytes(data: bytes, subs: List[Tuple[bytes, bytes]]) -> bytes:
    for needle, repl in subs:
        if needle:
            data = data.replace(needle, repl)
    return data


def _digest(path: str, subs: List[Tuple[bytes, bytes]]) -> Optional[str]:
    try:
        with open(path, "rb") as fh:
            data = fh.read()
    except (IOError, OSError):
        return None
    return hashlib.sha256(_norm_bytes(data, subs)).hexdigest()


def _exec_bit(path: str) -> Optional[bool]:
    """True/False for the owner-exec bit; None when the path is unreadable."""
    try:
        return bool(os.stat(path).st_mode & 0o100)
    except OSError:
        return None


def _walk(root: str) -> List[str]:
    out: List[str] = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if name.endswith(SKIP_SUFFIX):
                continue
            full = os.path.join(dirpath, name)
            out.append(os.path.relpath(full, root))
    out.sort()
    return out


# Delivery routes whose DESTINATION relpath differs from the SOURCE relpath,
# measured from install.sh's copy functions (PLAN-183 §8.5.1, S324 census).
#
# This is an ENUMERATION, not an inversion: identity-first stays correct for
# every path the installer copies under the same relpath, and blind
# `templates/`-first would break all of them. Only the routes below need the
# override, because for them a homonym of the DESTINATION also exists at the
# repo root — a different framework artifact the adopter never received.
# Comparing against it reports the wrong CLASS (UNCLASSIFIED where the truth
# is STALE): that is defect D2, PLAN-183 §8.2.
#
# DEBT (named, PLAN-183 §8.5.2): this table must become SHARED data read by
# `_framework_manifest_set.sh` and `doctor.sh` too. A second copy in bash
# would be the "local branch that decides ownership" CLAUDE.md §4 forbids.
# Promoting it is a W5-b item; this module is the first consumer, not the
# owner.
_TEMPLATE_DELIVERED = {
    # destination -> real source under the checkout root
    "docs/BRANCH-PROTECTION.md": "templates/docs/BRANCH-PROTECTION.md",
    "docs/rotation-log.md": "templates/docs/rotation-log.md",
}

# Destinations delivered through a TRANSFORM: the bytes the adopter received
# exist nowhere in the checkout (install.sh:1496-1510 applies
# `sed s/{{OWNER_HANDLE}}/<handle>/`, 11 occurrences). Resolving them needs the
# substitution value from the TARGET's install-state, which this classifier
# does not read. Reporting None is deliberate fail-LOUD: better "source
# unknown" than silently comparing against this repository's own live
# `.github/CODEOWNERS` — the one file that carries the maintainer's real
# handle. Consuming install-state is a W5-b item.
_RENDERED_DELIVERED = {
    ".github/CODEOWNERS": "templates/.github/CODEOWNERS.template",
}


def _src_digest(root: str, rel: str, subs: List[Tuple[bytes, bytes]]) -> Optional[str]:
    """Source lookup by DELIVERY ROUTE, not by file existence.

    Identity-first (the pre-S324 behavior) is preserved as the DEFAULT and is
    correct for every identity-mapped delivery. It is wrong for the enumerated
    routes above; see PLAN-183 §8.2 for the measured signature and §8.5.1 for
    the three delivery routes.

    Returning None on a declared-but-absent source is intentional: an OLD pin
    may legitimately predate a template, and raising there would crash the
    classifier on a valid comparison. The guard against a typo in the tables
    lives in the unit test, which asserts every declared source exists at HEAD.
    """
    if rel in _RENDERED_DELIVERED:
        # Rendered at install time; unresolvable without the target's
        # substitution values. NEVER fall through to identity here.
        return None
    mapped = _TEMPLATE_DELIVERED.get(rel)
    if mapped is not None:
        return _digest(os.path.join(root, mapped), subs)
    for candidate in (os.path.join(root, rel), os.path.join(root, "templates", rel)):
        digest = _digest(candidate, subs)
        if digest is not None:
            return digest
    return None


def _matches(rel: str, pattern: str) -> bool:
    return re.search(pattern, rel) is not None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--a", required=True, help="route A tree (fresh install)")
    ap.add_argument("--b", required=True, help="route B tree (pinned install + upgrade)")
    ap.add_argument("--head-src", required=True, help="working-tree framework source")
    ap.add_argument("--pin-src", required=True, help="extracted <pin> framework source")
    ap.add_argument("--pin", required=True, help="the pinned tag name")
    ap.add_argument("--mode", required=True, help="ceremony mode of this fixture")
    ap.add_argument(
        "--extra-source",
        action="append",
        default=[],
        metavar="DIR",
        help=(
            "additional source root to FOLD to {SOURCE} during normalization "
            "(no content lookups happen against it). The driver passes the "
            "planted-source farm under --positive-control so that the control "
            "fails for the PLANTED reason and not for unfolded absolute paths."
        ),
    )
    args = ap.parse_args()

    a_root = os.path.abspath(args.a)
    b_root = os.path.abspath(args.b)
    head_src = os.path.abspath(args.head_src)
    pin_src = os.path.abspath(args.pin_src)

    # Normalization: an installed tree legitimately embeds its own absolute
    # target path and the absolute source path (PROTOCOL.md pointer, CLAUDE.md
    # bootstrap line). Those are INSTALLATION-INSTANCE facts, not framework
    # content, so they are folded to placeholders before hashing. Both the
    # logical and the realpath form are folded (macOS mktemp hands out
    # /var/... which is a symlink to /private/var).
    norm_roots = [
        (a_root, b"{TARGET}"),
        (b_root, b"{TARGET}"),
        (head_src, b"{SOURCE}"),
        (pin_src, b"{SOURCE}"),
    ]
    for extra in args.extra_source:
        norm_roots.append((os.path.abspath(extra), b"{SOURCE}"))
    subs: List[Tuple[bytes, bytes]] = []
    for root, token in norm_roots:
        for form in (root, os.path.realpath(root)):
            pair = (form.encode("utf-8"), token)
            if pair not in subs:
                subs.append(pair)
    # Longest needle first: /private/var/... must be folded before /var/...
    subs.sort(key=lambda p: len(p[0]), reverse=True)

    a_files = _walk(a_root)
    b_files = _walk(b_root)
    a_set = set(a_files)
    b_set = set(b_files)

    buckets: Dict[str, List[str]] = {
        "IDENTICAL": [],
        "PERSONALIZED": [],
        "STALE": [],
        "MISSING_IN_B": [],
        "UNCLASSIFIED": [],
        "ONLY_IN_B": [],
        "ONLY_IN_B_OUTSIDE_CLAUDE": [],
        "MODE_DIFF": [],
    }
    accepted_hits: List[Tuple[str, str]] = []      # (rel, reason)
    accepted_seen: Dict[int, int] = {}

    for rel in a_files:
        ha = _digest(os.path.join(a_root, rel), subs)
        hb = _digest(os.path.join(b_root, rel), subs)
        if hb is None:
            cls = "MISSING_IN_B"
        elif ha == hb:
            cls = "IDENTICAL"
        else:
            h_head = _src_digest(head_src, rel, subs)
            h_pin = _src_digest(pin_src, rel, subs)
            if h_head is not None and hb == h_head:
                cls = "PERSONALIZED"
            elif h_pin is not None and hb == h_pin and h_pin != h_head:
                cls = "STALE"
            else:
                cls = "UNCLASSIFIED"
        buckets[cls].append(rel)

        # Permission parity is a SEPARATE axis from bytes: `cp` dropping the
        # exec bit is a verified failure mode here (S286), and a byte-identical
        # hook that arrives non-executable is still a broken delivery.
        if hb is not None:
            xa = _exec_bit(os.path.join(a_root, rel))
            xb = _exec_bit(os.path.join(b_root, rel))
            if xa is not None and xb is not None and xa != xb:
                buckets["MODE_DIFF"].append(
                    "%s  (A exec=%s, B exec=%s)" % (rel, int(xa), int(xb))
                )

    for rel in b_files:
        if rel not in a_set:
            if args.mode == "user" and not rel.startswith(".claude/"):
                buckets["ONLY_IN_B_OUTSIDE_CLAUDE"].append(rel)
            else:
                buckets["ONLY_IN_B"].append(rel)

    # --- ACCEPTED absorption (only for divergent classes) -------------------
    for cls in ("UNCLASSIFIED", "STALE", "MISSING_IN_B", "PERSONALIZED"):
        keep: List[str] = []
        for rel in buckets[cls]:
            hit = None
            for idx, (pattern, modes, reason) in enumerate(ACCEPTED):
                if modes is not None and modes != args.mode:
                    continue
                if _matches(rel, pattern):
                    hit = (idx, reason)
                    break
            if hit is None:
                keep.append(rel)
            else:
                accepted_hits.append((rel, hit[1]))
                accepted_seen[hit[0]] = accepted_seen.get(hit[0], 0) + 1
        buckets[cls] = keep

    # --- KNOWN_OPEN absorption --------------------------------------------
    known_hits: Dict[str, List[str]] = {}
    for entry in KNOWN_OPEN:
        known_hits[str(entry["id"])] = []
    for entry in KNOWN_OPEN:
        modes = entry["modes"]
        if modes is not None and modes != args.mode:
            continue
        cls = str(entry["cls"])
        keep = []
        for rel in buckets.get(cls, []):
            if _matches(rel, str(entry["re"])):
                known_hits[str(entry["id"])].append(rel)
            else:
                keep.append(rel)
        buckets[cls] = keep

    # --- expect-path assertions -------------------------------------------
    expect_open: List[Dict[str, Optional[str]]] = []
    for entry in EXPECT_PATHS:
        modes = entry["modes"]
        if modes is not None and modes != args.mode:
            continue
        path = str(entry["path"])
        in_a = path in a_files
        in_b = path in b_set
        if not in_a or not in_b:
            entry = dict(entry)
            entry["_observed"] = "A=%s B=%s" % (
                "present" if in_a else "ABSENT",
                "present" if in_b else "ABSENT",
            )
            expect_open.append(entry)

    # --- VERSION untouched assertion (pairs with its ACCEPTED entry) -------
    version_note = ""
    version_fatal = False
    b_version = os.path.join(b_root, "VERSION")
    pin_version = os.path.join(pin_src, "VERSION")
    if os.path.exists(b_version):
        d_b = _digest(b_version, subs)
        d_pin = _digest(pin_version, subs)
        if d_pin is None:
            version_note = "pinned source has no VERSION — cannot assert 'untouched'"
            version_fatal = True
        elif d_b == d_pin:
            version_note = "B/VERSION byte-identical to %s source (untouched) — OK" % args.pin
        else:
            version_note = (
                "B/VERSION differs from the %s source: upgrade.sh TOUCHED the "
                "adopter's root VERSION, which OQ-3 forbids" % args.pin
            )
            version_fatal = True
    else:
        version_note = "no root VERSION in B (expected in --ceremony user)"

    # ------------------------------------------------------------------ report
    w = sys.stdout.write
    w("\n")
    w("---- parity classification (mode=%s) --------------------------\n" % args.mode)
    w("  inputs:\n")
    w("    A (fresh install)        : %s  [%d files]\n" % (a_root, len(a_files)))
    w("    B (pin %-8s + upgrade): %s  [%d files]\n" % (args.pin, b_root, len(b_files)))
    w("    head source              : %s\n" % head_src)
    w("    pinned source (%s)  : %s\n" % (args.pin, pin_src))
    w("    normalization            : %s\n"
      % ", ".join(sorted({t.decode() for _, t in subs})))
    w("  counts (UNDECLARED residue — declared paths are broken out below):\n")
    for cls in (
        "IDENTICAL", "PERSONALIZED", "STALE", "MISSING_IN_B",
        "UNCLASSIFIED", "ONLY_IN_B", "ONLY_IN_B_OUTSIDE_CLAUDE", "MODE_DIFF",
    ):
        w("    %-26s %5d%s\n" % (
            cls, len(buckets[cls]),
            "   <-- FATAL if non-zero" if cls in (
                "STALE", "MISSING_IN_B", "UNCLASSIFIED",
                "ONLY_IN_B_OUTSIDE_CLAUDE", "MODE_DIFF") else "",
        ))
    w("    %-26s %5d\n" % ("ACCEPTED (declared)", len(accepted_hits)))
    w("    %-26s %5d\n" % (
        "KNOWN-OPEN (declared)",
        sum(len(v) for v in known_hits.values()) + len(expect_open),
    ))

    if accepted_hits:
        w("\n  ACCEPTED divergence (by design / generated / adopter-owned):\n")
        for rel, reason in accepted_hits:
            w("    - %s\n        %s\n" % (rel, " ".join(reason.split())))
    w("\n  VERSION assertion: %s\n" % version_note)

    if buckets["PERSONALIZED"]:
        w("\n  ADVISORY — upgrade shipped CURRENT framework bytes but install\n"
          "  personalizes them ({{PROJECT_NAME}}-class placeholders survive an\n"
          "  upgrade). Content generation is correct; presentation is not.\n"
          "  %d path(s):\n" % len(buckets["PERSONALIZED"]))
        for rel in buckets["PERSONALIZED"][:20]:
            w("    - %s\n" % rel)
        if len(buckets["PERSONALIZED"]) > 20:
            w("    ... and %d more\n" % (len(buckets["PERSONALIZED"]) - 20))

    if buckets["ONLY_IN_B"]:
        w("\n  ADVISORY — upgrade over-delivery (`cp -R` drags what install's\n"
          "  selective walk never ships; ADR-155 pre-existing drift, opposite\n"
          "  direction from F3). %d path(s), first 15:\n" % len(buckets["ONLY_IN_B"]))
        for rel in buckets["ONLY_IN_B"][:15]:
            w("    - %s\n" % rel)

    rc = 0

    fatal_blocks = [
        ("MISSING_IN_B",
         "install delivered these; the upgrade never did — an upgraded adopter "
         "simply does not have them"),
        ("STALE",
         "the upgrade left the %s generation in place while the framework "
         "changed the file — F3's exact signature" % args.pin),
        ("UNCLASSIFIED",
         "diverges and matches NEITHER source generation — if this is a "
         "generated or adopter-owned path, DECLARE it in ACCEPTED with its "
         "authority; do not widen a pattern to make it disappear"),
        ("ONLY_IN_B_OUTSIDE_CLAUDE",
         "upgrade wrote outside .claude/ in --ceremony user mode, breaking the "
         "WS4 invariant the install advertises"),
        ("MODE_DIFF",
         "same path, different executable bit between the two routes — one of "
         "the two deliveries lost (or invented) +x; bytes-only comparison is "
         "blind to it and the file still does not run"),
    ]
    for cls, why in fatal_blocks:
        if buckets[cls]:
            rc = 1
            w("\n  FATAL [%s] — %s\n" % (cls, why))
            for rel in buckets[cls]:
                w("    - %s\n" % rel)

    if version_fatal:
        rc = 1
        w("\n  FATAL [VERSION] — %s\n" % version_note)

    # Mandatory-fire audit: a KNOWN_OPEN entry that matched nothing is a
    # declaration that outlived its bug.
    stale_ledger: List[str] = []
    for entry in KNOWN_OPEN:
        modes = entry["modes"]
        if modes is not None and modes != args.mode:
            continue
        if not known_hits[str(entry["id"])]:
            stale_ledger.append(str(entry["id"]))
    if stale_ledger:
        rc = 1
        w("\n  FATAL [ledger-rot] — KNOWN-OPEN entries matched NOTHING in this\n"
          "  run. The bug each names is closed; delete the entry from\n"
          "  KNOWN_OPEN in scripts/tests/_parity_classify.py so the gate cannot\n"
          "  carry a dead exception:\n")
        for eid in stale_ledger:
            w("    - %s\n" % eid)

    stale_accepted = [
        ACCEPTED[i][0] for i in range(len(ACCEPTED))
        if i not in accepted_seen
        and (ACCEPTED[i][1] is None or ACCEPTED[i][1] == args.mode)
    ]
    if stale_accepted:
        w("\n  WARNING — declared ACCEPTED patterns that matched nothing in this\n"
          "  mode. For a GENERATED path that means the declaration is dead and\n"
          "  should go; for a PRESERVE-CONTRACT path (agent-metrics, CLAUDE.md,\n"
          "  MEMORY.md) it just means the template did not change between the\n"
          "  two generations, which is expected. Informational, never fatal:\n")
        for pattern in stale_accepted:
            w("    - %s\n" % pattern)

    outstanding = [e for e in KNOWN_OPEN
                   if (e["modes"] is None or e["modes"] == args.mode)
                   and known_hits[str(e["id"])]]
    if outstanding or expect_open:
        if rc == 0:
            rc = 2
        w("\n  KNOWN-OPEN (PLAN-166 W1 prerequisites — NAMED, never a silent\n"
          "  skip; this is why the run is red today):\n")
        for entry in outstanding:
            w("    [%s] class=%s\n" % (entry["id"], entry["cls"]))
            w("        paths     : %s\n" % ", ".join(known_hits[str(entry["id"])]))
            w("        why open  : %s\n" % " ".join(str(entry["reason"]).split()))
            w("        unblocked : %s\n" % " ".join(str(entry["unblocked_by"]).split()))
        for entry in expect_open:
            w("    [%s] class=expect-path\n" % entry["id"])
            w("        path      : %s (%s)\n" % (entry["path"], entry["_observed"]))
            w("        why open  : %s\n" % " ".join(str(entry["reason"]).split()))
            w("        unblocked : %s\n" % " ".join(str(entry["unblocked_by"]).split()))

    w("\n  verdict(mode=%s): %s\n" % (
        args.mode,
        {0: "PARITY", 1: "FAIL", 2: "KNOWN-OPEN"}[rc],
    ))
    w("--------------------------------------------------------------\n")
    return rc


if __name__ == "__main__":
    sys.exit(main())
