#!/usr/bin/env python3
"""generate-dispatch.py — auto-generate .claude/agents/_dispatch.md.

PLAN-020 Phase 1 (ADR-050 §Decision item 3). Single source of truth
for native-rail dispatch. Reads .claude/agents/*.md, parses YAML
frontmatter, emits a deterministic Markdown table.

Adopters / CEO never hand-edit `_dispatch.md` — it's regenerated by
`validate-governance.sh` and committed alongside changes to native
agent files.

## Wire-up

`validate-governance.sh` runs:

    python3 .claude/scripts/generate-dispatch.py --check

`--check` exits 0 if the on-disk `_dispatch.md` matches what would be
generated, else exits 1 with a diff (CI fail signal).

`--write` regenerates and overwrites `_dispatch.md` (commit the change).

## Schema

For each `.claude/agents/<slug>.md` file (excluding `_*.md`):
- Read YAML frontmatter
- Require keys: `name`, `description`, `version`
- Optional: `tools` (list)
- Compute SKILL.md @reference + sha256 from body if present

Output table columns: name | version | description | tools | skill-ref-hash
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple


REPO_ROOT = Path(
    os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
).resolve()
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
DISPATCH_PATH = AGENTS_DIR / "_dispatch.md"


_FRONTMATTER_RE = re.compile(
    r"\A---\n(.*?)\n---\n(.*)\Z",
    flags=re.DOTALL,
)
_SKILL_REF_LINE_RE = re.compile(
    r"^@(?P<path>\S+)[ \t]+sha256=(?P<hash>[0-9a-f]{64})\b",
    flags=re.MULTILINE,
)


@dataclass
class AgentEntry:
    slug: str  # filename stem (e.g. "code-reviewer")
    name: str
    version: str
    description: str
    tools: List[str]
    skill_path: Optional[str]
    skill_hash: Optional[str]
    model: str  # PLAN-021 ADR-052: model ID or "" (inherit)
    # PLAN-137 A3-parse: additional native harness fields. Parsed +
    # validated (see validate_frontmatter) but NOT rendered into
    # _dispatch.md — the table is byte-frozen by CI (--check), so adding
    # columns here would make the on-disk file go stale. These exist to
    # give validate_frontmatter a real consumer (the --validate gate),
    # turning a would-be bare parser into an active fail-closed validator.
    skills: List[str]  # native `skills:` list (default [])
    max_turns: Optional[int]  # native `maxTurns:` int or None (absent)
    isolation: str  # native `isolation:` enum {"none","worktree"} or ""


def parse_yaml_simple(fm_text: str) -> dict:
    """Stdlib-only minimal YAML for our needs (key: value + key: [list])."""
    result = {}
    current_key = None
    for raw_line in fm_text.splitlines():
        line = raw_line.rstrip()
        if not line or line.startswith("#"):
            continue
        if line.startswith(" ") or line.startswith("\t"):
            # continuation (we don't support multi-line strings here)
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1].strip()
            items = [
                item.strip().strip('"').strip("'")
                for item in inner.split(",")
                if item.strip()
            ]
            result[key] = items
        elif value.startswith('"') and value.endswith('"'):
            result[key] = value[1:-1]
        elif value.startswith("'") and value.endswith("'"):
            result[key] = value[1:-1]
        else:
            result[key] = value
        current_key = key  # noqa: F841
    return result


def _coerce_optional_int(value) -> Optional[int]:
    """Best-effort int coercion for a raw frontmatter scalar.

    Returns an int ONLY for a clean integer token (``"5"``, ``5``). Returns
    None for absent / non-integer / float / blank values. This is a
    *recorder*, not a validator — ``validate_frontmatter`` is the authority
    that REJECTS malformed values. We deliberately do not accept floats:
    ``"3.5"`` -> None so the AgentEntry carries no bogus int.
    """
    if value is None:
        return None
    if isinstance(value, bool):
        # bool is an int subclass; a YAML bool is not a turn count.
        return None
    if isinstance(value, int):
        return value
    text = str(value).strip()
    if not text:
        return None
    # int(text) accepts a leading sign + digits; rejects "3.5", "abc".
    try:
        return int(text)
    except (TypeError, ValueError):
        return None


def validate_frontmatter(fm: dict, slug: str) -> List[str]:
    """Validate the OPTIONAL native harness fields of one agent's frontmatter.

    Returns a list of human-readable error strings (empty list = valid).
    FAIL-CLOSED: a present-but-malformed value is an error. ABSENT fields are
    always OK — the 13 real agents today carry none of these, so an absent
    field must validate cleanly (backward compatible).

    Rules (PLAN-137 A3-parse gate):
      * ``maxTurns`` (if present): a positive integer. Reject ``"abc"``,
        ``"0"``, ``"-1"``, ``"3.5"``, blank, bool.
      * ``isolation`` (if present): one of {``none``, ``worktree``}.
      * ``skills`` (if present): a list. Reject a bare scalar.
    """
    errors: List[str] = []

    # --- maxTurns: present => positive integer -------------------------------
    if "maxTurns" in fm:
        raw = fm["maxTurns"]
        coerced = _coerce_optional_int(raw)
        if coerced is None:
            errors.append(
                "{}: maxTurns must be a positive integer, got {!r}".format(
                    slug, raw
                )
            )
        elif coerced <= 0:
            errors.append(
                "{}: maxTurns must be a positive integer (> 0), got {!r}".format(
                    slug, raw
                )
            )

    # --- isolation: present => enum {none, worktree} -------------------------
    if "isolation" in fm:
        raw_iso = fm["isolation"]
        if not isinstance(raw_iso, str) or raw_iso not in ("none", "worktree"):
            errors.append(
                "{}: isolation must be one of {{none, worktree}}, got {!r}".format(
                    slug, raw_iso
                )
            )

    # --- skills: present => list (reject a bare scalar) ----------------------
    if "skills" in fm:
        raw_skills = fm["skills"]
        if not isinstance(raw_skills, list):
            errors.append(
                "{}: skills must be a list, got {!r}".format(slug, raw_skills)
            )

    return errors


def parse_agent_file(path: Path) -> Optional[AgentEntry]:
    """Parse a `.claude/agents/<slug>.md` file into its frontmatter + body."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return None
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return None
    fm_text, body = m.group(1), m.group(2)
    fm = parse_yaml_simple(fm_text)
    if "name" not in fm:
        return None

    skill_match = _SKILL_REF_LINE_RE.search(body)
    skill_path = skill_match.group("path") if skill_match else None
    skill_hash = skill_match.group("hash") if skill_match else None

    # PLAN-137 A3-parse: native harness fields. `skills:` is a [list];
    # `maxTurns:` is a scalar we coerce to int best-effort (None if absent
    # or non-integer — validate_frontmatter is the authority that REJECTS
    # malformed values, parse just records a clean int when it can);
    # `isolation:` is a scalar string ("" if absent).
    raw_skills = fm.get("skills")
    skills = raw_skills if isinstance(raw_skills, list) else []
    max_turns = _coerce_optional_int(fm.get("maxTurns"))
    isolation = fm.get("isolation", "") or ""

    return AgentEntry(
        slug=path.stem,
        name=fm.get("name", ""),
        version=fm.get("version", ""),
        description=fm.get("description", ""),
        tools=fm.get("tools") or [],
        skill_path=skill_path,
        skill_hash=skill_hash,
        model=fm.get("model", "") or "",
        skills=skills,
        max_turns=max_turns,
        isolation=isolation,
    )


def collect_agents() -> List[AgentEntry]:
    if not AGENTS_DIR.is_dir():
        return []
    entries = []
    for path in sorted(AGENTS_DIR.glob("*.md")):
        if path.stem.startswith("_"):  # skip _dispatch, _probe_*, etc.
            continue
        entry = parse_agent_file(path)
        if entry is not None:
            entries.append(entry)
    return entries


def validate_all_agents() -> List[str]:
    """Run validate_frontmatter over every real agent file.

    Returns an aggregated list of error strings across all
    ``.claude/agents/<slug>.md`` files (excluding ``_*.md``). This is the
    REAL consumer wired into the ``--validate`` CLI mode and
    validate-governance.sh — without it the new frontmatter fields would be
    dead code (the anti-pattern PLAN-137 forbids).
    """
    errors: List[str] = []
    if not AGENTS_DIR.is_dir():
        return errors
    for path in sorted(AGENTS_DIR.glob("*.md")):
        if path.stem.startswith("_"):  # skip _dispatch, _probe_*, etc.
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            continue
        m = _FRONTMATTER_RE.match(text)
        if not m:
            continue
        fm = parse_yaml_simple(m.group(1))
        if "name" not in fm:
            continue
        errors.extend(validate_frontmatter(fm, path.stem))
    return errors


def render_dispatch_md(entries: List[AgentEntry]) -> str:
    """Render a spawn-dispatch markdown block from parsed agent frontmatter."""
    lines = []
    lines.append("# `.claude/agents/_dispatch.md` — auto-generated, DO NOT EDIT")
    lines.append("")
    lines.append(
        "Generated by `.claude/scripts/generate-dispatch.py`. Modifying this"
    )
    lines.append(
        "file directly will be reverted by CI. To change dispatch, edit the"
    )
    lines.append("source `.claude/agents/<slug>.md` files and re-run:")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 .claude/scripts/generate-dispatch.py --write")
    lines.append("```")
    lines.append("")
    lines.append("## Dispatch table")
    lines.append("")
    if not entries:
        lines.append("_(No native agent files found.)_")
        return "\n".join(lines) + "\n"
    lines.append(
        "| Slug | Name | Version | Model | Tools | Skill ref hash | Description |"
    )
    lines.append(
        "|------|------|---------|-------|-------|----------------|-------------|"
    )
    for e in entries:
        tools_str = ",".join(e.tools) if e.tools else "—"
        hash_short = (e.skill_hash[:8] + "…") if e.skill_hash else "—"
        # Short model label for dispatch table legibility.
        model_short = (
            "opus-4.7" if e.model == "claude-opus-4-7"
            else "sonnet-4.6" if e.model == "claude-sonnet-4-6"
            else "haiku-4.5" if e.model.startswith("claude-haiku-4-5")
            else "(inherit)" if not e.model
            else e.model
        )
        # Escape pipes in description for table safety
        desc = e.description.replace("|", "\\|")
        if len(desc) > 90:
            desc = desc[:87] + "…"
        lines.append(
            f"| `{e.slug}` | {e.name} | {e.version} | `{model_short}` "
            f"| `{tools_str}` | `{hash_short}` | {desc} |"
        )
    lines.append("")
    lines.append("## Provenance")
    lines.append("")
    lines.append(f"- Total agents: {len(entries)}")
    lines.append(f"- Source dir: `.claude/agents/`")
    lines.append(
        "- Generator: `.claude/scripts/generate-dispatch.py` "
        "(stdlib-only)"
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    """CLI entrypoint — generate a spawn-dispatch markdown from a plan."""
    parser = argparse.ArgumentParser(
        description="Generate or check .claude/agents/_dispatch.md"
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if on-disk _dispatch.md doesn't match generated.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write generated content to _dispatch.md (overwrite).",
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help=(
            "Validate optional native frontmatter fields (maxTurns/isolation/"
            "skills) across every agent; exit 1 if any file is invalid."
        ),
    )
    args = parser.parse_args()

    # PLAN-137 A3-parse: --validate is the active consumer of the parsed
    # native fields. Independent of --check/--write (which stay identical).
    if args.validate:
        errors = validate_all_agents()
        if errors:
            for err in errors:
                print("FAIL: {}".format(err), file=sys.stderr)
            print(
                "FAIL: {} frontmatter validation error(s) across "
                "agent files.".format(len(errors)),
                file=sys.stderr,
            )
            return 1
        print("OK: all agent frontmatter valid (maxTurns/isolation/skills)")
        return 0

    if not args.check and not args.write:
        # Default: print to stdout
        entries = collect_agents()
        sys.stdout.write(render_dispatch_md(entries))
        return 0

    entries = collect_agents()
    generated = render_dispatch_md(entries)

    if args.write:
        AGENTS_DIR.mkdir(parents=True, exist_ok=True)
        DISPATCH_PATH.write_text(generated, encoding="utf-8")
        print(f"OK: wrote {DISPATCH_PATH}")
        return 0

    if args.check:
        if not DISPATCH_PATH.is_file():
            print(
                f"FAIL: {DISPATCH_PATH} does not exist. "
                "Run with --write.",
                file=sys.stderr,
            )
            return 1
        on_disk = DISPATCH_PATH.read_text(encoding="utf-8")
        if on_disk != generated:
            print(
                f"FAIL: {DISPATCH_PATH} is stale. "
                "Run: python3 .claude/scripts/generate-dispatch.py --write",
                file=sys.stderr,
            )
            # Print short diff hint
            on_lines = on_disk.splitlines()
            gen_lines = generated.splitlines()
            print(
                f"  on-disk = {len(on_lines)} lines, "
                f"generated = {len(gen_lines)} lines",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {DISPATCH_PATH} is up-to-date ({len(entries)} agents)")
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
