#!/usr/bin/env python3
"""Regenerate the `Current ADRs` table in `.claude/adr/README.md`.

PLAN-045 F-06-02 — ADR index was stale (5 rows for 64 files on disk).
This script walks `.claude/adr/ADR-*.md`, parses each ADR's title +
status, and rewrites the table between `<!-- BEGIN ADR-INDEX -->` /
`<!-- END ADR-INDEX -->` markers.

## Parsing rules

Two ADR formats are supported:

1. **Legacy markdown header** (ADR-001 .. ADR-061):
   - Title: `# ADR-NNN: <title>` on line 1-3
   - Status: `**Status:** <value>` or `Status: <value>` in top 25 lines

2. **YAML frontmatter** (ADR-062+):
   - `id: ADR-NNN`
   - `title: <title>`
   - `status: <value>`

Status values are normalized to one of:
- `ACCEPTED`
- `PROPOSED`
- `SUPERSEDED` (with optional `by ADR-NNN` suffix)
- `DEPRECATED`
- `ACCEPTED-as-RESERVED`

## Usage

    python3 .claude/scripts/generate-adr-index.py --check   # exit 1 if drift
    python3 .claude/scripts/generate-adr-index.py --write   # rewrite README

## Canonical-edit sentinel

The target file `.claude/adr/README.md` is canonical-guarded. Running
`--write` produces edits that will be blocked by `check_canonical_edit.py`
unless an Owner-signed sentinel covers the path. Use `--check` in CI;
`--write` during a sentinel-gated round (e.g. PLAN-045 round-9).

## Exit codes

- 0: success (or no drift on --check)
- 1: drift detected (--check)
- 2: parse error (malformed ADR frontmatter)

## Ownership

Added PLAN-045 Session 45 Free-tier (C) sweep. Future sessions may
wire this into `validate-governance.sh` via `--check` once ADR-005
event stream SemVer rules permit a new validation step.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ADR_DIR = REPO_ROOT / ".claude" / "adr"
README_PATH = ADR_DIR / "README.md"

BEGIN_MARKER = "<!-- BEGIN ADR-INDEX (generated by .claude/scripts/generate-adr-index.py) -->"
END_MARKER = "<!-- END ADR-INDEX -->"

# Heading form: `# ADR-049a: title`, `# ADR-019-AMEND-1: title`,
# `# ADR-104-AMEND-1 — title`. Capture the full suffixed id token plus the
# title; the title group tolerates `:` or em/en-dash separators.
_TITLE_HEADER_RE = re.compile(
    r"^#\s+ADR-(\d+(?:-AMEND-\d+)?[a-z]?)\s*[:—–-]?\s*(.*)$", flags=re.MULTILINE
)
_YAML_TITLE_RE = re.compile(
    r"^title:\s*(.+)$", flags=re.MULTILINE
)
_YAML_STATUS_RE = re.compile(
    r"^status:\s*(.+)$", flags=re.MULTILINE
)
_YAML_ID_RE = re.compile(
    r"^id:\s*(.+)$", flags=re.MULTILINE
)
_MD_STATUS_RE = re.compile(
    r"^\*\*Status:\*\*\s*(.+)$|^Status:\s*(.+)$|^##\s+Status:?\s*(.+)$",
    flags=re.MULTILINE,
)
# Strip a leading `ADR-049a` / `ADR-019-AMEND-1` echo (with optional
# `:` / em-dash separator) from a parsed title so the index column does
# not repeat the id that already lives in the first column.
_TITLE_ID_ECHO_RE = re.compile(
    r"^\s*ADR-\d+(?:-AMEND-\d+)?[a-z]?\s*[:—–-]?\s*", flags=re.IGNORECASE
)


def _normalize_status(raw: str) -> str:
    """Reduce noisy status strings to a canonical short form."""
    raw = raw.strip()
    raw = re.sub(r"\*+", "", raw)
    raw = raw.split(" — ")[0].strip()
    raw = raw.split(" (")[0].strip()
    lowered = raw.lower()
    if lowered.startswith("superseded"):
        # preserve "SUPERSEDED by ADR-NNN" if present
        m = re.search(r"by\s+(ADR-\d+)", raw, re.IGNORECASE)
        if m:
            return f"SUPERSEDED by {m.group(1)}"
        return "SUPERSEDED"
    if lowered.startswith("accepted-as-reserved") or lowered.startswith("accepted as reserved"):
        return "ACCEPTED-as-RESERVED"
    if lowered.startswith("accepted"):
        return "ACCEPTED"
    if lowered.startswith("proposed"):
        return "PROPOSED"
    if lowered.startswith("deprecated"):
        return "DEPRECATED"
    return raw.upper()[:40]


def _display_id_from_filename(name: str) -> Optional[str]:
    """Derive the display id (`ADR-049a`, `ADR-019-AMEND-1`) from a filename.

    Returns ``None`` for a non-ADR filename. The numeric core is zero-padded
    to 3 digits; an optional ``-AMEND-N`` segment and a trailing lowercase
    ``a``-style suffix are preserved so amendment/clarifier files keep a
    distinct label in the index (no more collapsing to the base id).
    """
    m = re.match(r"^ADR-(\d+)(-AMEND-\d+)?([a-z])?", name)
    if not m:
        return None
    num = int(m.group(1))
    amend = m.group(2) or ""
    suffix = m.group(3) or ""
    return "ADR-{n:03d}{a}{s}".format(n=num, a=amend, s=suffix)


def _sort_key_from_filename(name: str) -> Tuple[int, int, str]:
    """Natural sort key: numeric, then base-before-`a`-suffix, then AMEND order.

    A base ADR (`ADR-049`) sorts before its `a`-clarifier (`ADR-049a`) and
    before its amendments (`ADR-049-AMEND-1`). Amendments sort by number.
    """
    m = re.match(r"^ADR-(\d+)(?:-AMEND-(\d+))?([a-z])?", name)
    if not m:
        return (10 ** 9, 0, name)
    num = int(m.group(1))
    amend = int(m.group(2)) if m.group(2) else 0
    suffix = m.group(3) or ""
    # rank: base (0) < a-suffix (1) < AMEND (2); within AMEND, by amend number
    if amend:
        rank = 2
    elif suffix:
        rank = 1
    else:
        rank = 0
    return (num, rank, "{a:03d}{s}".format(a=amend, s=suffix))


def _parse_adr(path: Path) -> Optional[Tuple[str, str, str]]:
    """Return (display_id, title, status) for an ADR file, or None on error."""
    adr_id = _display_id_from_filename(path.name)
    if adr_id is None:
        return None

    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None

    title: Optional[str] = None
    status: Optional[str] = None

    # Try YAML frontmatter first (newer format). Some amendment ADRs carry a
    # very large frontmatter block (multi-KB `amends:` arrays), so locate the
    # closing `---` over the FULL content, not a fixed-size prefix window.
    stripped = content.lstrip()
    if stripped.startswith("---"):
        lead = len(content) - len(stripped)
        fm_end = content.find("\n---", lead + 3)
        if fm_end > 0:
            fm = content[lead + 3:fm_end]
            m_t = _YAML_TITLE_RE.search(fm)
            m_s = _YAML_STATUS_RE.search(fm)
            if m_t:
                title = m_t.group(1).strip().strip('"').strip("'")
            if m_s:
                status = m_s.group(1).strip().strip('"').strip("'")

    # Fallback: markdown heading (only scan the head for performance)
    top = content[:4000]
    if title is None:
        m = _TITLE_HEADER_RE.search(top)
        if m:
            title = m.group(2).strip()

    # Fallback: markdown status
    if status is None:
        m = _MD_STATUS_RE.search(top)
        if m:
            status = next(g for g in m.groups() if g)

    # Last resort: a `status:` line in an embedded/below-heading frontmatter
    # block (some amendment ADRs put a `# ADR-NNN-AMEND-N` heading FIRST,
    # then a `---`-fenced YAML block with the canonical `status:`).
    if status is None:
        m = _YAML_STATUS_RE.search(top)
        if m:
            status = m.group(1).strip().strip('"').strip("'")

    if not title:
        title = "(untitled)"
    else:
        # Drop a leading `ADR-NNN[...]:` echo so the title column is clean.
        title = _TITLE_ID_ECHO_RE.sub("", title).strip() or title
    if not status:
        status = "(unknown)"

    return adr_id, title, _normalize_status(status)


def _collect_adrs() -> List[Tuple[str, str, str, Path]]:
    """Return a list of (id, title, status, path) for every ADR on disk."""
    entries: List[Tuple[str, str, str, Path]] = []
    paths = sorted(ADR_DIR.glob("ADR-*.md"),
                   key=lambda p: _sort_key_from_filename(p.name))
    for path in paths:
        parsed = _parse_adr(path)
        if parsed is None:
            print(f"parse error: {path.name}", file=sys.stderr)
            sys.exit(2)
        adr_id, title, status = parsed
        entries.append((adr_id, title, status, path))
    return entries


def _render_table(entries: List[Tuple[str, str, str, Path]]) -> str:
    """Render the markdown table for the ADR index."""
    lines: List[str] = []
    lines.append(BEGIN_MARKER)
    lines.append("")
    lines.append(f"_Auto-generated: {len(entries)} ADR(s) on disk. Run "
                 "`python3 .claude/scripts/generate-adr-index.py --write` to refresh._")
    lines.append("")
    lines.append("| ID | Title | Status |")
    lines.append("|---|---|---|")
    for adr_id, title, status, path in entries:
        safe_title = title.replace("|", "\\|")
        lines.append(f"| [{adr_id}]({path.name}) | {safe_title} | {status} |")
    lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines)


def _apply_table_to_readme(new_table: str, dry_run: bool = False) -> bool:
    """Rewrite the README between the markers. Returns True if changed."""
    content = README_PATH.read_text(encoding="utf-8")

    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER),
        flags=re.DOTALL,
    )

    if pattern.search(content):
        new_content = pattern.sub(new_table, content)
    else:
        # First-time install: insert after the "## Current ADRs" heading
        heading_re = re.compile(r"^## Current ADRs\s*$", flags=re.MULTILINE)
        m = heading_re.search(content)
        if not m:
            print("cannot find '## Current ADRs' heading in README.md",
                  file=sys.stderr)
            sys.exit(2)
        insert_at = m.end()
        # Find and drop the legacy 5-row table (everything up to the next
        # `##` heading or `## Why retroactive ADRs` section)
        next_heading = re.search(
            r"^## [A-Z]", content[insert_at:], flags=re.MULTILINE
        )
        if next_heading is None:
            print("cannot find next heading after '## Current ADRs'",
                  file=sys.stderr)
            sys.exit(2)
        tail_start = insert_at + next_heading.start()
        new_content = (
            content[:insert_at]
            + "\n\n"
            + new_table
            + "\n\n"
            + content[tail_start:]
        )

    if new_content == content:
        return False
    if not dry_run:
        README_PATH.write_text(new_content, encoding="utf-8")
    return True


def main() -> int:
    """CLI entrypoint — regenerate .claude/adr/README.md index table."""
    parser = argparse.ArgumentParser(description=__doc__.strip().split("\n")[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true",
                       help="exit 1 if README drifts from disk truth")
    group.add_argument("--write", action="store_true",
                       help="rewrite README.md (canonical — needs sentinel)")
    group.add_argument("--print", action="store_true",
                       help="print generated table to stdout")
    args = parser.parse_args()

    entries = _collect_adrs()
    table = _render_table(entries)

    if args.print:
        print(table)
        return 0

    if args.check:
        drift = _apply_table_to_readme(table, dry_run=True)
        if drift:
            print(f"DRIFT: README.md ADR index stale ({len(entries)} ADRs on disk)",
                  file=sys.stderr)
            return 1
        print(f"OK: README.md ADR index matches disk ({len(entries)} ADRs)")
        return 0

    if args.write:
        changed = _apply_table_to_readme(table, dry_run=False)
        if changed:
            print(f"OK: regenerated README.md ADR index ({len(entries)} ADRs)")
        else:
            print(f"OK: README.md ADR index already in sync ({len(entries)} ADRs)")
        return 0

    return 0


if __name__ == "__main__":
    sys.exit(main())
